[package]
name = "symtool"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"

[dependencies]
symtool-backend = { version = "0.1", path = "../symtool-backend" }
clap = "2.33"
regex = "1"
goblin = "0.0.24"
hashbrown = "0.6"
