[package]
name = "objedit"
version = "0.1.0"
authors = ["Caleb Zulawski <caleb.zulawski@gmail.com>"]
edition = "2018"

[dependencies]
goblin = "0.0.24"
scroll = "0.9.2"
clap = "2.33"
regex = "1"
ar = "0.8.0"
