name: Create Release Artifacts
on: [push]
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - linux-x86_64
        - macos-x86_64
        - windows-x86_64
        include:
        - build: linux-x86_64
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
        - build: macos-x86_64
          os: macOS-latest
          target: x86_64-apple-darwin
        - build: windows-x86_64
          os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
    - name: Strip
      if: contains(matrix.build, 'linux')
      run: strip -s symtool/target/${{ matrix.target }}/release/symtool
    - name: Strip
      if: contains(matrix.build, 'macos')
      run: strip symtool/target/${{ matrix.target }}/release/symtool
    - name: Package tar.gz
      if: contains(matrix.build, 'linux') || contains(matrix.build, 'macos')
      run: tar -czvf symtool.tar.gz -C symtool/target/${{ matrix.target }}/release/ symtool
    - name: Package zip
      if: contains(matrix.build, 'windows')
      run: Compress-Archive symtool/target/${{ matrix.target }}/release/symtool.exe symtool.zip
      shell: powershell
    - name: Upload tar.gz
      if: contains(matrix.build, 'linux') || contains(matrix.build, 'macos')
      uses: actions/upload-artifact@master
      with:
        name: symtool-${{ matrix.build }}.tar.gz
        path: symtool.tar.gz
    - name: Upload zip
      if: contains(matrix.build, 'windows')
      uses: actions/upload-artifact@master
      with:
        name: symtool-${{ matrix.build }}.zip
        path: symtool.zip
