name: Create Release Artifacts
on:
  push:
    tags:
    - 'v*'
jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - linux-x86_64
        - macos-x86_64
        - windows-x86_64
        include:
        - build: linux-x86_64
          os: ubuntu-latest
          target: x86_64-unknown-linux-musla
          type: tar.gz
        - build: macos-x86_64
          os: macOS-latest
          target: x86_64-apple-darwin
          type: tar.gz
        - build: windows-x86_64
          os: windows-latest
          target: x86_64-pc-windows-msvc
          type: zip
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --target ${{ matrix.target }} --manifest-path=symtool/Cargo.toml
    - name: Package tar.gz
      if: !contains(${{ matrix.os }}, 'windows')
      run: tar -czvf symtool.tar.gz -C symtool/target/release symtool
    - name: Package zip
      if: contains(${{ matrix.os }}, 'windows')
      run: Compress-Archive symtool/target/release/symtool.exe symtool.zip
    - name: Upload tar.gz
      uses: actions/upload-artifact@master
      if: !contains(${{ matrix.os }}, 'windows')
      with:
        name: symtool-${{ matrix.build }}.tar.gz
        path: symtool.tar.gz
    - name: Upload zip
      uses: actions/upload-artifact@master
      if: contains(${{ matrix.os }}, 'windows')
      with:
        name: symtool-${{ matrix.build }}.zip
        path: symtool.zip
